### ISSUE TITLE
Dark Mode - Icon Not visible Mobile

### ISSUE THREAD

**Issue by app-generator** [app-generator/cth-datta-able-dark#1]
![dark-mode-icon-issue](https://user-images.githubusercontent.com/51070104/175960933-85b51cdf-8e85-4814-98d6-4a1b60fe08a6.gif)

**Comment by ahmed-alii** [comment]
Noted. Will resolve asap.

**Comment by ahmed-alii** [comment]
Resolved.

**Comment by app-generator** [comment]
Validated. 
Ty @ahmed-alii for the fix.
